Feature/messages
ghosts-network/gateway pull request #65
Opened 2022-08-12 12:41 UTC by Sekir0

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Select single relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✓ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [✓ ] I have performed a self-review of my code
- [ ✓] My code follows the style guidelines and my changes generate no new warnings
- [ ✓] I have added tests that prove my fix is effective or that my feature works

2022-08-13 11:14 UTC, volodymyr-borodin requested changes

2022-08-13 11:14 UTC, volodymyr-borodin commented on GhostNetwork.Gateway.Api/Messages/MessagesController.cs
> +        if (chat is null || message is null)
same for delete

2022-08-13 11:14 UTC, volodymyr-borodin commented on GhostNetwork.Gateway.Infrastructure/ChatStorage.cs
> +    private static Chat ToGatewayChat(GhostNetwork.Messages.Model.Chat chat)
use explicit operator for simple convertions

2022-08-13 11:14 UTC, volodymyr-borodin commented on GhostNetwork.Gateway.Api/Messages/MessagesController.cs
> +    public async Task<ActionResult<Message>> GetByIdAsync([FromRoute] string chatId, [FromRoute] string messageId)
What's the use case for this endpoint?

2022-08-13 11:14 UTC, volodymyr-borodin commented on GhostNetwork.Gateway.Api/Messages/MessagesController.cs
> +[Route("{chatId}/messages")]
don't you forget some part of the route?

2022-08-13 11:14 UTC, volodymyr-borodin commented on GhostNetwork.Gateway.Api/Messages/MessagesController.cs
> +    public async Task<ActionResult<Message>> CreateAsync([FromRoute] string chatId, [FromBody] CreateMessage model)
Please rename to `SendAsync`

2022-08-13 11:14 UTC, volodymyr-borodin commented on GhostNetwork.Gateway.Infrastructure/ChatStorage.cs
> +            return DomainResult.Error("API error!");
Expose error details

2022-08-13 11:14 UTC, volodymyr-borodin commented on GhostNetwork.Gateway.Api/Chats/ChatsController.cs
> +    public async Task<ActionResult> UpdateAsync([FromRoute] string id, [FromBody] UpdateChat model)
Add validation (not more than 10 participants) and Chat name length from 5 to 256 chars

2022-08-18 14:31 UTC, volodymyr-borodin approved these changes

2022-08-18 14:35 UTC, volodymyr-borodin commented
There are 2 comments left. Others marked as resolved

2022-08-19 10:04 UTC, Sekir0 commented
> There are 2 comments left. Others marked as resolved

But GetById endpoint is already removed from controller
And participants validation is in MessageValidator.cs

2022-08-22 17:29 UTC, volodymyr-borodin commented on GhostNetwork.Gateway/Messages/MessageValidator.cs
> +            errors.Add(new DomainError("You is not a participant of the chat!"));
You is

2022-08-22 17:32 UTC, volodymyr-borodin approved these changes

2022-08-22 17:33 UTC, merged

2022-08-22 17:33 UTC, volodymyr-borodin commented
You did a great job